#global:
#  scrape_interval: 15s
#  scrape_configs:
#    - job_name: 'spring_boot_app'
#      metrics_path: '/actuator/prometheus'
#      static_configs:
#        - targets: ['Springusers-env.eba-macic9ka.eu-central-1.elasticbeanstalk.com:5000']
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring_boot_app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['Springusers-env.eba-macic9ka.eu-central-1.elasticbeanstalk.com']
